version: "3"
services:
  webtop:
    build: .
    image: ghcr.io/itxve/chrome-flash
    container_name: local-chrome-flash
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 9900:3000
      - 9001:3001
    # devices:
      # - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped