version: "3"
services:
  webtop:
    # image: webtop-local-webtop
    build: .
    image: xfce-flash-webtop
    container_name: local-bb-xfce-webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - ./mt/:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 9900:3000
      - 9001:3001
    # devices:
      # - /dev/dri:/dev/dri #optional
    shm_size: "2gb" #optional
    restart: unless-stopped